// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vchkghowtuuhhvvbmbul.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZjaGtnaG93dHV1aGh2dmJtYnVsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTA5NDAwNTgsImV4cCI6MjA2NjUxNjA1OH0.c_Z72-5-b3_0LpPAN0dcAUe6ljNww5lWb3FR-5IjRbc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);